### ISSUE TITLE
Restore system backup does not work on a fresh installation

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#183] opened 2020-05-02 11:48 UTC
**Describe the bug**
Restoring a system backup on a fresh installation does not reinstall the hardware-setup

**To Reproduce**
1. Created a fresh SD from 2020-04-23-zynthianos-buster-lite-1.0.0.img
2. Booted from this SD (on the disco-Zynthian aka Zynthian-v1)
3. Logged into webconf and restored last system-backup
4. Screen is white again - webconf is running and showing, that Kit-v3 is still selected.

**Expected behavior**
I thought the backup should  restore the full system as when the backup is made.

**Screenshots**
...

**Setup:**
 - 2020-04-23-zynthianos-buster-lite-1.0.0.img
 - Hardware:
Raspberry Pi 4 Model B Rev 1.1
Soundcard: HifiBerry DAC+
Display: PiTFT 2.8 Resistive
Wiring: PROTOTYPE-3H
GPIO Expander: MCP23008
 - Software:
zyncoder: master (c9a395c)
zynthian-ui: master (926af8e)
zynthian-sys: master (cc93f7f)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
Also my Pianoteq licenses and binaries are not restored. After manual setting up the hardware I saw that PT-6.6-Trial is installed. So the system-backup is IMHO not working.

**Comment by riban-bw** [comment] 2021-03-18 07:48
Duplicate of #121

**Closed by riban-bw** 2021-03-18 07:48 UTC
