### ISSUE TITLE
Issue: Wifi connection details not re-configurable in zynthian-UI (ORAM)

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1014] opened 2024-03-26 08:45 UTC
# Describe the issue
Changing the once set Wifi access password in the UI of zynthian, it is not re-configurable anymore
# To Reproduce
## Steps to reproduce the behavior:
1. Choose wifi connection
2. set wrong password for wifi password
3. -> can't connect message appears
4. try to re-enter the password again not possible anymore
 ## Expected behaviour
After can't connect message, there should be the possibility to change the password again,
and it would be nice to get eventually more information about what was going wrong.
## Actual behaviour
No possibility to change a once configured password.
# Screenshots
# Additional context

If I understand the code of zynthian_gui_wifi.py correctly, the configuration is only called once, but no check for the result of enable_wifi_nw() leads to the call of the configure_wifi() again, hence - once configured (wrongly) → no chance to change the pwd. But maybe I’m wrong code-wise.
This most likely is connected to the use of nmcli called from zynthian_gui_wifi.py . 
nmcli saves configurations under /etc/NetworkManager/system-connections/WLANNameXYZ.nmconnection and analyzing of the command line result for the "nmcli --terse con up " call.

Solution idea: press on learn/shot knob or bold press on select knob ->  keyboard input screen would solve this issue.

# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 17% (654M/3792M)
SD Card: 29% (16G/58G)
Temperature: 44.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (8b6b74f)
zynthian-sys: oram (609b7e7)
zynthian-data: oram (97355e2)
zynthian-webconf: oram (4c5d7a5)
```

**Comment by jofemodo** [comment] 2024-04-23 10:59
I can't reproduce. It works for me. Could you confirm the issue with the last updates?

**Comment by riban-bw** [comment] 2024-05-01 11:06
This does not always happen but sometimes, after a failed connection attempt the UI returns to the list of WiFi APs and does not show the keyboard. This might be a timing issue with screens being closed when not expected.

**Comment by jofemodo** [comment] 2024-06-04 19:34
I can't reproduce. Let's close this and let's create new tickets for different issues.

**Closed as completed by jofemodo** 2024-06-04 19:34 UTC
Labels: Can't reproduce
