### ISSUE TITLE
Remove "Long Press Select" as power off.

### ISSUE THREAD

**Issue by smiths73v3** [zynthian/zynthian-issue-tracking#252] opened 2020-08-16 23:46 UTC
**Is your feature request related to a problem? Please describe.**
Zyncoder frequently fails to detect button release detection for "select knob." This causes power-off confirmation screen to appear, disrupting work flow, and risking inadvertent power down of zynth.

**Describe the solution you'd like**
Ignoring long press select has worked well for me, No ill effects have been seen. Unit can be powered off by long press of back button, and selecting "power off" item from admin menu.

**Describe alternatives you've considered**
-none

**Additional context**
`zynthian_gui.py`
`+               #elif i==3:`
`+               #       self.screens['admin'].power_off()`

**Comment by jofemodo** [comment] 2020-08-17 00:30
Sorry, i can't reproduce the issue. For me it's working OK 100% of times.
Probably your encoder/switch is kind of broken ...

**Comment by smiths73v3** [comment] 2020-08-17 00:39
I've tried swapping out the encoder, and have used different cables. The issue is still nagging for months, this solution works well for me. This was the easiest way to fix.

 I'll take a look at the zyncoder module again. This seems like a missed interrupt on the release button press, or release while processing the press event. Either of these fixes will be difficult to detect, and resolve.

**Comment by jofemodo** [comment] 2020-08-17 00:39
Wait a moment ... you are not using the standard kit, but your own EPDF kit.  What encoders/swtiches are you using? Does include debouncing circuitry for encoder and switch? Have you tested them with a oscilloscope?

The zyncoder includes software debouncing, but there is a limit to what can be done by software... hardware debouncing is also needed.

**Comment by smiths73v3** [comment] 2020-08-17 00:40
Hmm, yes. I think this might be a debouncing issue. I have not attached an oscilloscope yet.

**Comment by jofemodo** [comment] 2020-08-17 00:44
All i can say is that with the "official" kit this never happened to me ... recently ... I remember the initial days, before i added the debouncing capacitors ...  and the most strange things happened every day ;-D

**Comment by smiths73v3** [comment] 2020-08-17 00:59
Yeah, I was hoping to use off the shelf encoders. I'll do some scope traces and compare with the "official" encoder schematic.

This one change makes the worst symptom of debouncing go away. The other occasional glitches are hardly noticeable.

**Comment by jofemodo** [comment] 2020-08-17 01:10
But we don't want the symptoms go away ... we want to fix the real problem, no? };-)
Think that software debouncing consumes "high priority CPU cycles" on the ISRs, and we should avoid this waste of CPU on ISRs because it could cause XRuns due to the fact that these hardware IRQs are not preemptible ...

Also, everybody is used to looong select to power off .... i won't change this for one person's issue.

Cheers,

**Comment by jofemodo** [comment] 2020-08-17 01:11
I close the issue, but please, keep me informed about your progress with it ... OK?
We can use this thread although it's closed ...

**Closed by jofemodo** 2020-08-17 01:12 UTC

**Comment by smiths73v3** [comment] 2020-08-17 01:13
Sounds good Thanks!
