### ISSUE TITLE
Normalize function on Audio Recorder.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1199] opened 2024-09-16 10:16 UTC
**Is your feature request related to a problem? Please describe.**
Audio recordings need normalising for more consistent use further down the production chain. 

**Describe the solution you'd like**
Whilst stopped a function can be applied to the audio sample such that the highest recorded peak is placed at a proscribed level below full scale deflection.

**Describe alternatives you've considered**
I bounce the audio out to audacity and do it there, than bounce it back to the zynth.

**Comment by riban-bw** [comment] 2024-10-03 04:39
Would we add another controller to normalise? It would probably need to confirm yes/no. That could be technically challenging. Could this be a webconf option? Should there be an admin option to normalise at end of recording? Should we add an option to the preset options menu?

None of the above seem optimal operationally or coding. Any further suggestions?

**Comment by riban-bw** [comment] 2024-11-02 08:47
Duplicate of #1117.

**Closed as completed by riban-bw** 2024-11-02 08:47 UTC
Labels: Duplicate
