### ISSUE TITLE
Audio Player Waveform build fails

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1115] opened 2024-07-09 09:44 UTC
# Describe the issue
Attempting to use the audio player. The waveform display hangs ....
Happens on all audio files tried...  (can't upload wav files here...)

IndexError: invalid index to scalar variable.
Traceback (most recent call last):
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 603, in refresh_gui
    self.draw_waveform(offset, int(self.frames / self.zoom))
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 491, in draw_waveform
    av = a[frame][channel] * self.v_zoom
         ~~~~~~~~^^^^^^^^^
IndexError: invalid index to scalar variable.
libzynaudioplayer exiting...  done!
/zynthian/config/img/fb_zynthian_message.png is 1x1 PNG image, color type GRAY, 8 bit
  Zooming image by 108000%...done
  Merging...done
  Building XImage...done
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
(venv) root@zynthian-cajon2:/zynthian/zynthian-ui# git status
On branch oram
Your branch is up to date with 'origin/oram'.

nothing to commit, working tree clean

1. Go to Audio Player via vnc.
2. Select Audio sample (WAV)
4. See error
 ## Expected behaviour
The Waveform display should populate.
## Actual behaviour

Traceback (most recent call last):
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 603, in refresh_gui
    self.draw_waveform(offset, int(self.frames / self.zoom))
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 491, in draw_waveform
    av = a[frame][channel] * self.v_zoom
         ~~~~~~~~^^^^^^^^^

```
## Software
zyncoder: [oram (628f3fb)](https://github.com/zynthian/zyncoder/commit/628f3fbece66d0cff76f4508f93d37feacd780d5)
zynthian-ui: [oram (d8293a5)](https://github.com/zynthian/zynthian-ui/commit/d8293a59c8ab656c01c1b3f43cbc9ff7698db902)
zynthian-sys: [oram (4461148)](https://github.com/zynthian/zynthian-sys/commit/44611486f45552061e376cdc43f980e26f5b322b)
zynthian-data: [oram (e222e11)](https://github.com/zynthian/zynthian-data/commit/e222e116a1967e38075a96e2bf25aa051f796d30)
zynthian-webconf: [oram (f31699f)](https://github.com/zynthian/zynthian-webconf/commit/f31699f8fd37e1ccd287f9ee1624c938ddb4994d)
```

**Comment by wyleu** [comment] 2024-07-09 10:09
[Uploading last_state.zip…]()

Contains snapshot and audio file

**Comment by oscaracena** [comment] 2024-08-20 10:08
I did not see this issue when I submitted mine, sorry @wyleu! 😅 Nevertheless, is the same as #1145 so @riban-bw you may close this one :)

**Comment by riban-bw** [comment] 2024-08-20 18:56
This looks like the same issue affecting mono audio files only which is now fixed.

**Comment by oscaracena** [comment] 2024-08-21 11:23
Hi @riban-bw! Sorry for bumping you here... 😅 I've got an MP3 example (stereo) that produces the same problem (`IndexError`), but the cause is different (is related to the first index). The result is the same, the waveform could not be created. 

This is a traceback of a raised exception:

```
IndexError: index 2678665 is out of bounds for axis 0 with size 2678400
Traceback (most recent call last):
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 607, in refresh_gui
    self.draw_waveform(offset, int(self.frames / self.zoom))
  File "/zynthian/zynthian-ui/zyngui/zynthian_widget_audioplayer.py", line 494, in draw_waveform
    av = a[frame][channel] * self.v_zoom
         ~^^^^^^^
```

And this is the file that produces it:

* [stereo-track.zip](https://github.com/user-attachments/files/16690761/stereo-track.zip)

**Comment by riban-bw** [comment] 2024-08-21 18:35
This looks like a fence post error but I haven't yet figured out where.

**Comment by riban-bw** [comment] 2024-08-22 06:27
It was actually an problem reading data which gave different length to requested / expected. Should be fixed now. I tested with the attached audio and all other audio files on my system.

**Comment by oscaracena** [comment] 2024-08-22 09:12
Thank you @riban-bw for your quick response and fix! It now works... well, most of the time... 😅 It sometimes just hangs, but now I did not see any error message. It appears to be a random problem. (some sort of condition race?) I know these are harder to debug. 😞 I've recorded some evidence:

[zynsampler-waveform-issue.webm](https://github.com/user-attachments/assets/b92c449d-47e7-4788-af00-d79b7d008db0)

I'm sorry for bothering you so much!

**Comment by riban-bw** [comment] 2024-08-22 09:26
Interesting. I haven't seen that behaviour with any of my files. Will you please find a file that it happens on and upload it here? Is there any pattern, e.g. does it always fail on some files? Does it only fail on some but never on others?

**Comment by oscaracena** [comment] 2024-08-22 09:48
I don't see a pattern. A file that does not load one time, it may load correctly later. Sometimes I have the issue on the second try, and sometimes it need more time. I have the files on an old 8 GiB USB drive (ext4), could it be related? I've not seen any error message with `dmesg` about the drive. 

I've got some files, and with them I can recreate the problem easily. I attach them in a ZIP file, keeping their names and folder structure.

[sample-tracks.zip](https://github.com/user-attachments/files/16708630/sample-tracks.zip)

Hope it helps! 😃

**Comment by oscaracena** [comment] 2024-08-22 10:28
The problem appears to be with the widgets. The waveform is correctly populated, but for some reason, the "loading" label is not hidden (or the waveform widget not shown).

**Comment by riban-bw** [comment] 2024-08-22 10:47
I still can't reproduce this and inexplicably, can't find any working USB memory sticks to test your workflow! Will you please trigger the issue and then change the "Info" parameter (on the 5th parameter page) to see if that shows the waveform?

**Comment by oscaracena** [comment] 2024-08-22 11:05
Yes, changing the info param redraws the waveform, and it shows properly. This gives you any clue?

**Closed as completed** 2024-08-22 11:25 UTC

**Comment by oscaracena** [comment] 2024-08-22 11:30
Adding the following line (zynthian_widget_audioplayer.py:614) also fixes the issue:

```diff
  if self.refresh_waveform:
      self.draw_waveform(offset, int(self.frames / self.zoom))
+     self.widget_canvas.itemconfig("waveform", state=tkinter.NORMAL)
      refresh_markers = True
```

I know it may not be a solution, but it gives more context info. It occludes the label in case the waveform could not be loaded for legit reasons.
