### ISSUE TITLE
When Creating a new Synthesizer Layer, Selecting SetBfree will lock up the UI

### ISSUE THREAD

**Issue by jerrynsr** [zynthian/zynthian-issue-tracking#492] opened 2021-08-10 12:30 UTC
Test Branch: UI Locks up when selecting the setBfree synthesizer for later

**To Reproduce**
1. Switch to test branch
2. Install New layer
3. Select SetBfree
4. Assign to any layer of your choosing
5. UI will freeze

**Expected behavior**
UI should return back with the sub menu to select the type of setBfree synthesizer to setup... followed with main/effects/portamento setup for the layer.

**Setup:**
 - SD-image 
 05-24-16:39 zynthianos-last-stable.zip
 - Hardware Config
 - Kit:           Custom
Display:       Pi 7 Touchscreen Display 800x480
Soundcard:     HifiBerry DAC+ ADC
Wiring Layout: DUMMIES

 - Software Version
 zynthian-ui: testing (21a764)
 zynthian-webconf: testing (38d33e)
 zyncoder: testing (26ffae)
 zynthian-sys: testing (574c78)
 zynthian-data: testing (315390)

**Additional context**
I enable UI log debugging, Here's the output:
Aug 10 00:34:13 zynthian startx[21084]: DEBUG:zynthian_engine.start: Command: setBfree -p “/zynthian/zynthian-data/setbfree/pgm/all.pgm” -c “/zynthian/config/setbfree/.autogen.cfg”
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_engine_setbfree.set_bank: Loading manuals configuration program: 59
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_zcmidi.set_midi_prg: Set MIDI CH 5, Program: 59
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_engine_setbfree.set_bank: STARTING SETBFREE!!
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_engine_setbfree.set_bank: Loading manuals configuration program: 59
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_zcmidi.set_midi_prg: Set MIDI CH 5, Program: 59
Aug 10 00:34:14 zynthian startx[21084]: DEBUG:zynthian_engine_setbfree.get_preset_list: Preset List for Bank FAVS
Aug 10 00:34:14 zynthian startx[21084]: ERROR:zynthian_engine_setbfree.load_program_list: Getting program info from FAVS => [Errno 2] No such file or directory: ‘FAVS’
Aug 10 00:34:14 zynthian startx[21084]: ERROR:zynthian_gui.zyncoder_read: ‘NoneType’ object is not iterable
Aug 10 00:34:14 zynthian startx[21084]: Traceback (most recent call last):
Aug 10 00:34:14 zynthian startx[21084]: File “./zynthian_gui.py”, line 1269, in zyncoder_read
Aug 10 00:34:14 zynthian startx[21084]: self.zynswitch_defered_exec()
Aug 10 00:34:14 zynthian startx[21084]: File “./zynthian_gui.py”, line 1218, in zynswitch_defered_exec
Aug 10 00:34:14 zynthian startx[21084]: self.zynswitch_short(event[1])
Aug 10 00:34:14 zynthian startx[21084]: File “./zynthian_gui.py”, line 1166, in zynswitch_short
Aug 10 00:34:14 zynthian startx[21084]: self.screens[self.active_screen].switch_select(‘S’)
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py”, line 251, in switch_select
Aug 10 00:34:14 zynthian startx[21084]: self.click_listbox(None, t)
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py”, line 247, in click_listbox
Aug 10 00:34:14 zynthian startx[21084]: self.select_action(self.index, t)
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_bank.py”, line 73, in select_action
Aug 10 00:34:14 zynthian startx[21084]: self.zyngui.show_screen(‘preset’)
Aug 10 00:34:14 zynthian startx[21084]: File “./zynthian_gui.py”, line 430, in show_screen
Aug 10 00:34:14 zynthian startx[21084]: self.screens[screen].show()
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_preset.py”, line 59, in show
Aug 10 00:34:14 zynthian startx[21084]: super().show()
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py”, line 126, in show
Aug 10 00:34:14 zynthian startx[21084]: self.fill_list()
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngui/zynthian_gui_preset.py”, line 48, in fill_list
Aug 10 00:34:14 zynthian startx[21084]: self.zyngui.curlayer.load_preset_list()
Aug 10 00:34:14 zynthian startx[21084]: File “/home/pi/zynthian-ui/zyngine/zynthian_layer.py”, line 196, in load_preset_list
Aug 10 00:34:14 zynthian startx[21084]: for preset in self.engine.get_preset_list(self.bank_info):
Aug 10 00:34:14 zynthian startx[21084]: TypeError: ‘NoneType’ object is not iterable

**Comment by jofemodo** [comment] 2021-08-12 12:09
Sorry, i can't reproduce this issue. I've tested with 2 different zynthians, including a fresh burned+updated SD and setBfree works perfectly OK for me. Please, try to reproduce the issue again and give an accurate list of steps for reproducing it. Ideally starting from a fresh-burned SD.

Regards,

**Comment by jofemodo** [comment] 2021-08-13 23:36
Hi @jerrynsr !

I close the issue. I would open it again if you give us accurate steps for reproducing.

Thanks,

**Closed as completed by jofemodo** 2021-08-13 23:36 UTC
Labels: Can't reproduce
