### ISSUE TITLE
state of "Enable multichannel recording" is not saved permanently in oram bookworm

### ISSUE THREAD

**Issue by gitnob** [zynthian/zynthian-issue-tracking#1012] opened 2024-03-21 15:44 UTC
# Describe the issue
state of "Enable multichannel recording" is not saved permanently in oram-bookworm-64 (updated 2024/03/21)
# To Reproduce
## Steps to reproduce the behavior:
1. Go to webconf
2. Click on "Enable multichannel recording"
3. Save

 ## Expected behaviour
State of multichannel recording button to be saved
## Actual behaviour
No state saving
# Screenshots

# Configuration

## Hardware
Raspberry Pi 4 Model B Rev 1.2
Audio: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
I2C: MCP23017@0x20
Profile: v4_stage

Debian GNU/Linux 12 (bookworm)
Build Date: 2024-03-01
Memory: 16% (609M/3792M)
SD Card: 23% (13G/58G)
Temperature: 50.1ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 0 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (2a80116)
zynthian-sys: oram (609b7e7)
zynthian-data: oram (0db799e)
zynthian-webconf: oram (6a7f603)
```

**Comment by riban-bw** [comment] 2024-05-01 11:08
The webconf setting is no longer relevant. Multitrack recording is enabled by arming individual chains in the UI. We should remove the webconf setting.

**Comment by riban-bw** [comment] 2024-05-24 06:48
Duplicate of #960.

**Closed as completed by riban-bw** 2024-05-24 06:48 UTC
