### ISSUE TITLE
Changing MIDI channel of MIDI chain breaks

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#921] opened 2023-11-19 10:23 UTC
**Describe the bug**
After adding a MIDI chain, attempt to change its MIDI channel results in a non-working Zynthian with progress continually running.

**To Reproduce**
1. Clean all
2. Add MIDI chain with MIDI Thru plugin on MIDI CH#1
3. Press and hold SEL button to show Chain Options
4. Select "MIDI Channel"
5. Change channel to "MIDI CH#5"

**Expected behaviour**
Zynthian operates normally.

**Actual behaviour**
Loading icon animates continually. Cannot change MIDI channel. Error in log (see below).

**NOTE:** This did not reoccur on second attempt to reproduce so may be triggered by previous (unrecorded) actions. Hopefully the log will point to the issue.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://192.168.1.110/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://192.168.1.110/hw-display)
Wiring: [V5](http://192.168.1.110/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://192.168.1.110/hw-wiring)
Profile: [v5](http://192.168.1.110/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-08-25
Memory: 5% (213M/3839M)
SD Card: 50% (14G/29G)
Temperature: 45.7ºC
Overclock: [Maximum](http://192.168.1.110/hw-options)
- MIDI
Profile: [default.sh](http://192.168.1.110/ui-midi-options)
Tuning: [440 Hz](http://192.168.1.110/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.1.110/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://192.168.1.110/ui-midi-options)
MIDI to Output: [Off](http://192.168.1.110/ui-midi-options)
Master Channel: [off](http://192.168.1.110/ui-midi-options)
- SOFTWARE
zyncoder: [testing (7ada795)](https://github.com/zynthian/zyncoder/commit/7ada795dfa0ab269bba18345d9712d64231c0c65)
zynthian-ui: [testing (5d8b779)](https://github.com/zynthian/zynthian-ui/commit/5d8b779ceeddccc902f4139fda8b60f7d532a3a7)
zynthian-sys: [testing (ad43f0a)](https://github.com/zynthian/zynthian-sys/commit/ad43f0abeaf8d08b689da5e8663d15e81589416d)
zynthian-data: [testing (1321e5d)](https://github.com/zynthian/zynthian-data/commit/1321e5d1ce0d75ef8963bf0f0c9a00218c748bb5)
zynthian-webconf: [testing (1d12e3f)](https://github.com/zynthian/zynthian-webconf/commit/1d12e3fb5b4a57c09473d69665227c0486bd7d1f)

**Additional context**
Log:
```
Nov 19 10:12:46 zynthian startx[488]: WARNING:zynthian_gui_config.set_midi_config: Bad MIDI Master Note CUIA config 59: => Bad format!
Nov 19 10:13:29 zynthian startx[488]: ERROR:zynthian_gui_layer_options.setup: No layer index!
Nov 19 10:13:31 zynthian startx[488]: ERROR:zynthian_gui.zynswitch_read: 'NoneType' object has no attribute 'midi_chan'
Nov 19 10:13:31 zynthian startx[488]: Traceback (most recent call last):
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 2029, in zynswitch_read
Nov 19 10:13:31 zynthian startx[488]:     self.zynswitches()
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1815, in zynswitches
Nov 19 10:13:31 zynthian startx[488]:     self.zynswitch_timing(i, dtus)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1831, in zynswitch_timing
Nov 19 10:13:31 zynthian startx[488]:     self.zynswitch_short(i)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1953, in zynswitch_short
Nov 19 10:13:31 zynthian startx[488]:     self.custom_switch_ui_action(i-4, "S")
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1777, in custom_switch_ui_action
Nov 19 10:13:31 zynthian startx[488]:     self.callable_ui_action_params(cuia)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1182, in callable_ui_action_params
Nov 19 10:13:31 zynthian startx[488]:     self.callable_ui_action(cuia, params)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1160, in callable_ui_action
Nov 19 10:13:31 zynthian startx[488]:     cuia_func(params)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1665, in cuia_v5_zynpot_switch
Nov 19 10:13:31 zynthian startx[488]:     self.zynswitch_short(i)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1949, in zynswitch_short
Nov 19 10:13:31 zynthian startx[488]:     self.screens[self.current_screen].switch_select('S')
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 336, in switch_select
Nov 19 10:13:31 zynthian startx[488]:     self.click_listbox(None, t)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 330, in click_listbox
Nov 19 10:13:31 zynthian startx[488]:     self.select_action(self.index, t)
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer_options.py", line 236, in select_action
Nov 19 10:13:31 zynthian startx[488]:     self.list_data[i][0]()
Nov 19 10:13:31 zynthian startx[488]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer_options.py", line 270, in layer_midi_chan
Nov 19 10:13:31 zynthian startx[488]:     chan_list = self.zyngui.screens['layer'].get_free_midi_chans() + [self.layer.midi_chan]
Nov 19 10:13:31 zynthian startx[488]: AttributeError: 'NoneType' object has no attribute 'midi_chan'
```

**Comment by jofemodo** [comment] 2024-01-08 08:54
I can't reproduce. It seems to be fixed now.

**Closed as completed by jofemodo** 2024-01-08 08:54 UTC
