### ISSUE TITLE
Use single issue tracker

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#455] opened 2021-05-19 06:59 UTC
**Is your feature request related to a problem? Please describe.**
Having several different issue trackers, one for each software reprository adds overhead to issue management and can lead to confusion and incorrect referencing, e.g. referencing issue #nnn will refer to one repo not another. Metadata like milestones, labels, etc. need to be replicated. It is difficult to asses all the issues within a single milestone or relase. 

**Describe the solution you'd like**
Consolidate all issues into a single issue tracker. Ensure that all projects refer to the single tracker, e.g. #nnn refers to issue nnn in the global issue tracker.

**Describe alternatives you've considered**
There are workflows in place to manage multiple trackers and these could be enforced / better documented but I find them confusing and not intuitive so rarely follow them.

**Additional context**
Before I start working on an issue I feel like there is additional friction through the process to follow. Trying to track issues or refer to them can be awkward and I have often refered to an issue in git commits which have resulted in comments in the wrong issue due to the issue number and location having changed during triage. It can be cosidered good practice to refer to ticket numbers in version control (git) branch names which may lose relevance during triage. I guess there are benefits to the current system which I can not see so please do explain these benefits. I can only see disadvantages.

If this request were approved we could migrate issues slowly or even leave as is but stop moving issues to the other repros so that the problem eases over time. (I would prefer an effort to consolidtate the issues to a single tracker but that could be a slow background task rather than a big push.) We will want to retain (reinstate) any metadata of an issue.

**Comment by riban-bw** [comment] 2021-07-05 07:36
I have assigned this to @jofemodo and marked as urgent as I feel we need to decide this to facilitate more efficient issue management.

**Comment by jofemodo** [comment] 2021-07-05 11:26
The only advantage i see is using a simpler notation for referencing tickets from the commit text. You can use “#456” instead of “zynthian/zynthian-ui#456”.

Regarding the disadvantages:

+ from my point of view, the tiny overhead of moving the issue is not important
+ but having repeated ticket numbers can be confusing
+ and the metadata loss when moving is annoying
+ the worst is that many tasks (especially complex ones) are transversal, involving several code repositories, so moving the task to a particular repo is quite arbitrary

So, OK, let’s unify the tracking system.

For doing so, i would propose to do nothing. Simply change our workflow by don’t moving tasks to any particular code repo. We already have been doing this with some tasks. Let’s do it with all of them.

If somebody open a task on a particular code repo, what is rare, we can move it to the “Issue Tracker” repo.

Closing the issue trackers on the code repos is too disrupting and we will lost traceability of older tasks and will be forced to move currently open tasks, some of them already referenced by commits. Of course, we can do it later, if we find annoying to keep them open.

Regards,

**Closed** 2021-07-05 11:26 UTC
Labels: Urgent
