### ISSUE TITLE
Audio player speed change without pitch shift

### ISSUE THREAD

**Issue by sstojos** [zynthian/zynthian-issue-tracking#929] opened 2024-01-02 00:26 UTC
Current audio player only can change speed by changing a pitch. It would be great to be able to change speed but not a pitch.

zynthian can be used for practising where one layer can be audio player that plays backing track while another synth. It would be beneficial in this case to have a way for audio player to play backing track slower without a pitch change so that learning the part can first be done with a slower speed until it is mastered there before moving to right speed.

**Comment by jofemodo** [comment] 2024-01-02 20:26
I would like to have full control of speed and pitch from Audio Player. Something like this:

**Regarding Pitch Shifting:**

+ When played  C3, no pitch shifting should be performed, saving CPU.
+ When played any other note, pitch shifting is performed
+ It would be fantastic to "cache" pitch shifting calculations to save CPU

**Regarding Time Stretching:**

+ When recording, the sample should take the "nominal" tempo (BPM) from the current zynthian's BPM setting
+ When importing samples, zynthian should try to take it from file metadata or file name. A manual setting option should be available too.
+ When playing a sample, it should be "time-stretched" to the current zynthian's tempo setting (BPM). In order to save CPU, improve quality and avoid XRuns, Zynthian should precalculate and "cache" the stretched sample.

Regards,

**Comment by riban-bw** [comment] 2024-02-20 12:21
All implemented in oram branch. Now can:

- Change speed
- Change pitch
- Varispeed / scrub
- Change pitch with MIDI note & pitchbend
- Splice sample and play each splice at natural pitch from different MIDI notes

**Comment by sstojos** [comment] 2024-02-20 12:42
Great thanks @riban-bw ! I have just ordered another sd card to put your branch on to it for testing. Will let you know the results.

**Comment by sstojos** [comment] 2024-02-20 14:10
Hi @riban-bw , I have updated to your branch all repositories but my zyntian is erroring on boot. 

```
$ ssh -l root 192.168.1.220
root@192.168.1.220's password:

 ##########################       ----------------------------------------
#                          #      ZynthianOS: Built on os.zynthian.org
#            ##            #      Timestamp: 2023-08-25
#      ##   #  #   ##      #      Optimized: Raspberry Pi 3 Model B Plus
#     #  #  #  #  #  #     #      ----------------------------------------
###   #  #  #  #  #  #   ###      Kit:           Custom
#  #  #  #  #  #  #  #  #  #      Display:       MIPI DSI 800x480
#   ##   #  #  #  #   ##   #      Soundcard:     HifiBerry DAC+ light
#         ##    ##         #      Wiring Layout: DUMMIES
#                          #      ----------------------------------------
 ##########################
                                  zynthian-ui: oram (26370a)
                                  zynthian-webconf: oram (37d9e5)
                                  zyncoder: oram (9ea5d3)
                                  zynthian-sys: oram (5ea965)
                                  zynthian-data: oram (4555a9)
                                  ---------------------------------------
```

I have updated zynthian using CLI before switching to your branch.  Should I start with flashing latest sdcard image and then switch to your branch ?

**Comment by sstojos** [comment] 2024-02-20 14:20
Error is the following: 

```
DEBUG:zynthian_lv2.load_engines: Loading engine config failed: Expecting ':' delimiter: line 1 column 8207 (char 8206)
Traceback (most recent call last):
  File "./zynthian_main.py", line 34, in <module>
    from zyngine.zynthian_chain import *
  File "/home/pi/zynthian-ui/zyngine/__init__.py", line 25, in <module>
    from zyngine.zynthian_lv2 import *
  File "/home/pi/zynthian-ui/zyngine/zynthian_lv2.py", line 684, in <module>
    load_engines()
  File "/home/pi/zynthian-ui/zyngine/zynthian_lv2.py", line 172, in load_engines
    if not os.path.exists(ENGINE_CONFIG_FILE) or "ID" not in engines['AE']:
KeyError: 'AE'
```

**Comment by riban-bw** [comment] 2024-02-21 06:09
Try an update from webconf. The startup issue should be fixed.

**Closed as completed** 2024-02-21 08:53 UTC
Labels: Resolved

**Comment by sstojos** [comment] 2024-02-21 12:21
Update did now work either - now the erros is:

```
INFO:zynthian_engine_audioplayer.zynthian_engine_audioplayer: Supported Audio Codecs: ['aiff', 'aifc', 'au', 'caf', 'flac', 'mp3', 'vox', 'opus', 'ogg', 'wav']
DEBUG:zynthian_lv2.load_engines: Loading engine config failed: Expecting ':' delimiter: line 1 column 8207 (char 8206)
Traceback (most recent call last):
  File "./zynthian_main.py", line 36, in <module>
    from zyngui.zynthian_gui import zynthian_gui
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 47, in <module>
    from zyngine import zynthian_state_manager
  File "/home/pi/zynthian-ui/zyngine/zynthian_state_manager.py", line 49, in <module>
    from zyngine.zynthian_chain_manager import *
  File "/home/pi/zynthian-ui/zyngine/zynthian_chain_manager.py", line 1478, in <module>
    zynthian_chain_manager.get_engine_info()
  File "/home/pi/zynthian-ui/zyngine/zynthian_chain_manager.py", line 148, in get_engine_info
    cls.engine_info['PT']['TITLE'] = pt_info['name']
KeyError: 'PT'
```
I will wait for new stable release to test it

**Comment by riban-bw** [comment] 2024-02-22 07:07
@jofemodo This is caused by [this change](https://github.com/zynthian/zynthian-ui/commit/5e5dc5b2c34b2999be1be221dad003acfe5b290b#diff-887f1a11d0c26e559284eadfc99402961e90906b22f4426931a3a6747a4e3693R1448) which calls zynthian_chain_manager.get_engine_info() when chain_manager module is loaded but can cause key error on some systems.

**Comment by riban-bw** [comment] 2024-02-22 07:14
@sstojos When did you move to chain_manager branch? It may be that you have an old, partially populated engine config file. This is dynamically created at runtime. If you have one built during eary development phase then it is likely to be corrupt or incomplete. Please try deleting `/zynthian/config/engine_config.json` and retesting.

During development phase there are changes to various bits of code, config, etc. that may need manual intervention to resolve. We aim to ensure migration between stable releases do not encounter these issues but not between commits within a development cycle. (To do so would add too much _compatibility_ code.)
