### ISSUE TITLE
Mouse press on zynpad always plays sequence even if you try a bold press to activate pattern editor.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#356] opened 2021-02-22 13:10 UTC
**Describe the bug**
Upon pressing a mouse on an active zynpad pad the sequence plays even if you are holding for a bold press to access Pattern editor

**To Reproduce**
1. Go to sequencer
2. Bold press mouse on zynpad and add a pattern 
3. Go back to zynpad with sequence stopped
4. Press & hold mouse on pad to go into pattern editor of already written pattern.
5. Pattern plays 
6. Then it goes into pattern editor

**Expected behavior**
Go straight into pattern editor without pattern playing As happens with a bold press on the select encoder.

**Setup:**
 - SD-image
 - Hardware Config
 - Software Version
![image](https://user-images.githubusercontent.com/79083/108712842-4951f800-750f-11eb-88e8-e5013331014a.png)

**Additional context**
May be a wyleu only characteristic as with the play/stop buttons.

**Comment by riban-bw** [comment] 2021-02-23 22:37
This is a duplicate of #336. I had thought of stopping the sequencer on entering pattern editor but see that it should have same behaviour as pressing encoder.

I will close this ticket and address in #336.

**Closed by riban-bw** 2021-02-23 22:37 UTC
