### ISSUE TITLE
ORAM: split not working with 2 FluidSynth instrument chains

### ISSUE THREAD

**Issue by Piattica** [zynthian/zynthian-issue-tracking#1026] opened 2024-04-22 11:15 UTC
**Describe the bug**
ORAM update today: split does not work with 2 FluidSynth instrument chain

**To Reproduce**

I would like to do a split

step a: Active MIDI CHANNEL: ON
step b: Create instrument chain 1 with FluidSynth set on MIDI CHANNEL 1 from C-2 to A2
step c: Create instrument chain 2 with FluidSynth set on MIDI CHANNEL 1 from A#2 to G8

Result:
got instrument chain 1 and chain 2 are on all range

**Setup:**
 - SD-image: [ORAM 2403](https://os.zynthian.org/test/2024-03-01-zynthianos-bookworm-aarch64-oram-2403.zip)
 - Hardware Config: ZYNTHIAN V4
 Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://zynthian.local/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian.local/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian.local/hw-wiring)
I2C: [MCP23017@0x20](http://zynthian.local/hw-wiring)
Profile: [v4_stage](http://zynthian.local/hw-wiring)

 - Software Version:
 zyncoder: [oram (c575089)](https://github.com/zynthian/zyncoder/commit/c575089dba5e8eb32df94a63386f404ec4282205)
zynthian-ui: [oram (4daa3b2)](https://github.com/zynthian/zynthian-ui/commit/4daa3b20b5c6c8230cfd960f523d3868f5c1802c)
zynthian-sys: [oram (99700c2)](https://github.com/zynthian/zynthian-sys/commit/99700c2c9f6fd634bbab4fa5ecf7b51c4d6899a3)
zynthian-data: [oram (97355e2)](https://github.com/zynthian/zynthian-data/commit/97355e206fe63a954564cce08837d6c4a3c276d8)
zynthian-webconf: [oram (3f1dae4)](https://github.com/zynthian/zynthian-webconf/commit/3f1dae4c3e67ccb041f107cbb54fff488e50cf53)

**Comment by riban-bw** [comment] 2024-04-26 09:19
This is a duplicate of #927.

**Closed as completed by riban-bw** 2024-04-26 09:19 UTC
Labels: Duplicate
