### ISSUE TITLE
ADD MIDI note name to MIDI log display.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#860] opened 2023-03-29 14:11 UTC
**Is your feature request related to a problem? Please describe.**
Whilst setting up the zynseq I was keen to know which note my MIDI keyboard was generating.
The current MIDI display shows values.
![zynthian-midi-log](https://user-images.githubusercontent.com/79083/228565461-0728f73a-83e5-4264-b7bb-3f859ff81f74.png)

Could it display note names and octaves?. C4 etc...?

This would standardise the MIDI names we use in the sequencer and transpose mechanism.

**Comment by wyleu** [comment] 2023-03-29 15:41
Reflecting this information and, ideally, showing the key pressed in the keyboard display,  in the chain Note range & Transpose screen when the function is in not learning mode. 
Allowing examination and definition of midi transposition and range context, as it applies to the current chain.

It's very easy to get lost when setting many external devices up against the zynthian with limited sample maps and which key they relate to.

**Comment by riban-bw** [comment] 2024-02-24 16:39
Duplicate of #562

**Closed as completed by riban-bw** 2024-02-24 16:39 UTC
Labels: Duplicate
