### ISSUE TITLE
Issue:not handling chains with the same name properly in restore options

### ISSUE THREAD

**Issue by lanmower** [zynthian/zynthian-issue-tracking#1288] opened 2024-11-30 18:04 UTC
# Describe the issue
the checkbox list in restore options cant differentiate chains with the same name
# To Reproduce
## Steps to reproduce the behavior:
make 2 chains, dont rename them
go to restore options
they wont be differentiated, it will also cause a rendering glitch or two where they do get differentiated only if they have different checkbox states
 ## Expected behaviour
they should appear separately
## Actual behaviour
they appear to render as a single list item

# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Generic USB device
Display: Generic HDMI/DSI Display
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-10-02
Memory: 11% (962M/8048M)
SD Card: 34% (20G/59G)
Temperature: 57.1ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (66fa477) 
zynthian-ui: oram (7b68279)
zynthian-sys: oram (105c12d)
zynthian-data: oram (305b301)
zynthian-webconf: oram (31f3f55)
```

**Comment by riban-bw** [comment] 2024-12-22 07:41
This ticket is difficult to undertsand because it omits any reference to ZS3. This issue is that after saving a ZS3, the ZS3 Restore Options menu does not show chains with duplicate names.

**Comment by riban-bw** [comment] 2024-12-22 08:15
The cause is the options menu only allows unique option titles due to it using this as the dictionary key. As a dirty but effective (pragmatic) solution I have appended spaces to the end of any duplicate entries. This is fixed in vangelis (testing) ready for deploy to oram (stable) in next point release.

**Closed as completed** 2024-12-27 08:11 UTC
Labels: Resolved
