### ISSUE TITLE
MIDI-CC Learning should work across netwrks.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#192] opened 2020-05-06 07:58 UTC
**Is your feature request related to a problem? Please describe.**
Controlling Parameters remotely should be able to be configured remotely. 

**Describe the solution you'd like**
With a remote zynthian GUI available if I engage mid-cc learning it should learn a remote cc alteration.

**Describe alternatives you've considered**
Lots of config and jumping between machines.

**Additional context**
I'm doing a lot of remote zynthian bits and pieces and want to set up a multiple easy to use environment, that I can drive multiple synths from one master keyboard attached to a simple cut down synth....

**Comment by jofemodo** [comment] 2020-05-07 08:39
Do you mean that MIDI-learning workflow doesn't work when using RTP-MIDI or QMidiNet? ;-)

**Comment by wyleu** [comment] 2020-05-11 07:22
I can't get it working . . .

**Comment by wyleu** [comment] 2020-05-26 06:01
qmidiNet

**Comment by jofemodo** [comment] 2020-05-28 15:13
Hi @wyleu !

I just tested and it worked like a charm!
Please, could you give the details?

+ SD image version
+ Engine
+ Preset
+ Parameter name
+ Detailed Procedure you followed 

Regards!

**Comment by jofemodo** [comment] 2020-06-02 15:46
Hi @wyleu!
Please, re-confirm the issue and give me more details. It works for me and i can't reproduce the problem.

**Comment by jofemodo** [comment] 2020-06-10 01:50
Eoooo! @wyleu ... i couldn't reproduce the problem with QMidiNet ... it worked like a charm for me. Please, re-confirm the issue and give more details if it's not working for you ....

**Comment by jofemodo** [comment] 2020-06-12 01:34
OK! I close it.
Please, don't doubt to re-open if you reproduce the problem ...

**Closed by jofemodo** 2020-06-12 01:34 UTC
Labels: Can't reproduce
