### ISSUE TITLE
Bug: Sometimes a parameter will change its value when the corrsponding screen is scrolled past in the UI

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#596] opened 2022-01-15 11:12 UTC
**Describe the bug**
I have a snapshot where when I scroll through the parameter UI for for a layer with NoizeM4k3r, when I reach the 'Pitchwheel & Chorus' group, the 'chorus1' setting, which is ON in the patch, is turned off, without clicking select and actually editing the parameter (all parameters are still greyed in the display). The change of sound can be clearly heard if holding a note while scrolling through the  parameters.

After editing the parameter, and saving as a new snapshot, then loading it, it no longer exhibts the problem. After loading the old snapshot again the problem is there again.

**To Reproduce**
1. Load snapshot 015-Test redux.zss
2. In parameter UI, click select (parameters are greyed out).
3. Play a note on MIDI channel 3. Notice how note has chorus.
4. Slowly scroll through the parameters using the select knob
5. Note that when reaching the Pitchwheel & Chorus page, chorus1 is turned off (and displayed as such), and the resulting shift in sound can be clearly heard.

**Expected behavior**
Scrolling past parameters should never cause them to change their value.

**Setup:**
- SD image
2021-09-25-zynthianos-stable.img 
- HARDWARE: Zynthian kit v4.4 (4 GB)
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-25
Memory: 3% (121M/3839M)
SD Card: 44% (13G/29G)
Temperature: 48.2�C
- MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: [on]
- SOFTWARE
zyncoder: stable (7c09738)
zynthian-ui: stable (4a08200)
zynthian-sys: stable (e33fd3a)
zynthian-data: stable (018aa41)
zynthian-webconf: stable(39b61bb)

**Additional context**
I don't know if this is relevant, but the old snapshot was originally created before the recent update of the UI groups for NoizeM4k3r.

Originally the snapshot has lots of other layers. I removed them in order to verify that their presence wasn't the reason for the problem.

Problem snapshot: http://butoba.net/downloads/015-Test%20redux.zss
Edited and working snapshot: http://butoba.net/downloads/017-Test%20redux%20edited.zss
Original snapshot with all the original layers: http://butoba.net/downloads/014-Test.zss

**Comment by jofemodo** [comment] 2022-01-15 17:55
Did you create this snapshot before refactoring the NoizeMaker's TTL for implementing groups?

**Comment by polluxsynth** [comment] 2022-01-16 09:58
Yes, I think so.

**Comment by jofemodo** [comment] 2022-01-16 17:10
Could you try to recreate the snapshot and see if the problem persist?

**Comment by polluxsynth** [comment] 2022-01-17 06:02
I'll try to.

Even if it is a migration issue, it still seems a problem, if a user creates a snapshot with one TTL file, upgrades the Zynthian, and tries to use and edit the snapshot with another TTL file.

**Comment by jofemodo** [comment] 2022-01-17 08:14
I think i fix the problem. Could you update and try again with the old snapshot?

**Comment by polluxsynth** [comment] 2022-01-17 17:51
Which commit is it? I've had issues with old snapshots (the layers don't show up in the audio mixer even though I can hear them when plying) when using testing so for the time being I'm still on stable, so I need to bring in commits one by one. Had a quick look at the testing branch on zynthian-ui but couldn't see anything obvious. Or is it this one: bec624e80d3c6e2b35628679131626523760b7ac .

**Comment by jofemodo** [comment] 2022-01-17 22:49
If you have snapshots created with the stable branch or from before the new mixer deployment, you have to rebuild them. We are not going to implement a porting mechanism until we are ready to merge with stable again. Things are moving fast on testing these days, and it's only the beginning of a big wave of changes ... ;-)

**Comment by polluxsynth** [comment] 2022-01-18 00:24
I can understand that a porting mechanism for layers is not a priority at the moment, but the problem in this specific case is that the 'problem' snapshot I have was made on the stable branch, and if I load it in testing, I can hear the layer, but it does not show up in the audio mixer, and there is no longer a list of existing layers in the layer menu, so I can't reach it for editing so I can't verify your fix... Or is there some other way of reaching layers that don't show up in the audio mixer?

Otherwise, if I knew which commit(s) fix(es) the problem, I can cherry-pick them into my local stable, possibly with a bit of editing, in order to verify the fix.

**Comment by polluxsynth** [comment] 2022-01-21 23:30
I've been a bit at a loss verifying the fix, because I didn't know what I'd done to create the snapshot that exhibited the problem, and loading the problem snapshot into the testing branch didn't work because since there was no audio routing in the snapshot, I couldn't select the layer for editing...

However, I think I have found the part of the cause of the problem, and a possible workaround.

In the NoiseMaker ttl, there are a number of switched parameters which have the scale points 0.0 (OFF) and 1.0 (ON). However, expressed as continous parameters, they underlying function is switched on as soon as the value goes above 0, with the first click being 0.005. The problem seems to be that when the UI is using a ttl with the scale points for a certain parameter being 0.0 and 1.0, if the parameter value happens to be 0.005, which is sufficient for the parameter to be considered on, it is rounded down to 0.0, and is thus turned off. This was the case with my 'problem' snapshot: the chorus1 value was set to 0.005.

A solution or at least a workaround is to set the ON scale point for these parameters to 0.005 . I tested it and it works fine, both with snapshots which happen to have the parameter set to 0.005 (the "problem" snapshot, 015-Test redux.zss) and also the snapshot saved with the new ttl (017-Test redux edited.zss), where I'm supposing the parameter value is stored as 1.0 .

Indeed, this seems consistent with the scale points for other parameters, such as Portamento mode, where the scale points for OFF, Auto and ON are 0.0, 0.25 and 0.75, with these points being the lowest parameter value for which the underlying parameter assumes the state indicated. So it stands to reason, then, that parameters with two states should follow the same logic and have scale points of 0 and 0.005, assuming the underlying parameters switch state at these points, which seems to be the case for all parameters in the NoiseMaker.

I can prepare a PR for the NoiseMaker ttl, but I thought I'd bring it up to discussion here first if it is an acceptable solution. For one thing, it is mergable to stable, like the rest of the NoiseMaker ttl updates, which is a good thing.

**Comment by jofemodo** [comment] 2022-01-24 19:22
Could be related with this ticket:

https://github.com/zynthian/zynthian-issue-tracking/issues/540

**Comment by polluxsynth** [comment] 2022-01-25 07:12
Doesn't really sound like it, among other things, @riban-bw mentioned "I have observed volume changing to zero for Fluidsynth whilst output remained at normal volume." which does not sound like the bug in this thread, where the displayed value in the UI always matches the actual parameter value.

**Comment by riban-bw** [comment] 2022-04-28 03:51
I think this is resolved in masterfx branch. Adding "Resolved" flag and will request @polluxsynth test when released.

**Comment by polluxsynth** [comment] 2022-04-28 20:34
@riban-bw Do you mean the problem has been fixed globally, i.e. doesn't require adjustment of the individual .ttl's for each engine?

**Comment by riban-bw** [comment] 2022-04-29 07:47
The issue was that parameters changing value unexpectedly. I believe this is now resolved in the testing branch but has yet to be deployed to stable release hence I have marked the ticket as resolved pending testing either in the testing branch (that can be done now) or in the next stable release which is planned to land next month.

**Comment by riban-bw** [comment] 2022-10-20 14:03
Cannot reproduce in staging 2210 and believe it to have been fixed in testing some time ago so closing this issue.

**Closed as completed by riban-bw** 2022-10-20 14:03 UTC
Labels: Resolved

**Comment by polluxsynth** [comment] 2022-10-20 19:04
Yes, I haven't seen it for a long time now, at least not on Testing (haven't been on the stable branch for quite some time so I don't know what the state was there). I think the ticket was being held open until it was merged to stable so it certainly makes sense to close it.
