### ISSUE TITLE
Navigation issue between bank select and mixer view

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#612] opened 2022-02-20 07:37 UTC
**Describe the bug**
Navigating from bank selector to mixer view triggers an anonomally with subsequent navigation.

**To Reproduce**
1. From mixer view, short press SELECT to navigate to layer control view
2. Short  press BACK to select preset list
3. Short press BACK to select bank list
4. Bold press BACK to navigate to mixer view
5. Short press SELECT to navigate to layer control view

**Expected behaviour**
Control view displayed.

**Actual behaviour**
Bank list displayed.

6. Short press BACK

**Expected behaviour**
Control view displayed.

**Actual behaviour**
Mixer view displayed.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: [ZynADAC](http://zynthian1.4sar/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian1.4sar/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian1.4sar/hw-wiring)
GPIO Expander: [MCP23017](http://zynthian1.4sar/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 50% (937M/1872M)
SD Card: 63% (17G/29G)
Temperature: 52.5ºC
- SOFTWARE
zyncoder: [testing (1609f8d)](https://github.com/zynthian/zyncoder/commit/1609f8dc2c134e9e879bd29334f53513db1ff295)
zynthian-ui: [testing (f561029)](https://github.com/zynthian/zynthian-ui/commit/f56102902a3f27fb1cba7ce815078c161e284ea0)
zynthian-sys: [testing (587dd76)](https://github.com/zynthian/zynthian-sys/commit/587dd76365adbf6683b8477a4a129155fff20919)
zynthian-data: [testing (076a23d)](https://github.com/zynthian/zynthian-data/commit/076a23dd0084519e05981588f886c5d7d8a47e5e)
zynthian-webconf: [testing (0de7a5e)](https://github.com/zynthian/zynthian-webconf/commit/0de7a5e3b605e93077f3a950d8839199d2536512)

**Additional context**
Unexpected behaviour: Navigation from mixer view to control view the user expects to see control view, not bank select. This is confusing under normal workflows although may be expected if user has accidentally bold pressed from bank view. I suggest this is the corner case and behaviour should be that navigation from mixer to control views should always show controls, not bank.

Inconsistent behaviour: Short press from bank list shoudl navigate to control screen. Navigation to mixer view is inconsistent.

**Comment by riban-bw** [comment] 2022-02-20 07:45
I just tried to reproduce this and I think it is a bit more subtle. From engine control screen:

- Short BACK to show preset list
- Short BACK to show bank list
- Highlight different bank
- Short SELECT to select different bank and show preset list
- Bold BACK to show mixer view
- Short SELECT should show control screen but actually shows bank list (which isn't even where you were previously!)

**Comment by jofemodo** [comment] 2022-02-21 14:08
Sorry @riban-bw !!

I can't reproduce any of the workflows you describe here. Current workflow is like this (and it works consistently for me):

+ From Audio Mixer 
     + short select for accessing Layer Control 
     + bold select for acesssing Layer Options
+ From Layer Control
     + short back for accessing Preset List
     + short select for enter controller screen selection
     + bold select for acesssing Layer Options
+ From Preset List 
     + short back for accessing Bank list
     + short select for selecting preset
     + bold select for marking/unmarking as favorite
+ From Bank List
     + short back for going back to Layer Control
     + short/bold select for selecting bank
+ From any screen
     + bold-back for accessing audio mixer

Regards,

**Comment by riban-bw** [comment] 2022-02-21 20:28
Follow the steps in my second comment. I can reproduce on my other Zynthian.

- From mixer, short press to access layer control
- Short press BACK to access preset list
- Short press BACK to access bank list
- Use SELECT knob to highlight a **different bank**
- Short press SELECT to access preset list
- Bold press BACK to access mixer
- Short press SELECT to access layer control
Actually shows bank list.

**Comment by jofemodo** [comment] 2022-02-22 09:37
OK! I understand now. Let me see ...

**Comment by jofemodo** [comment] 2022-02-22 11:26
It should be fixed now. Please update & test!

**Closed as completed** 2022-02-22 11:26 UTC
