### ISSUE TITLE
snapshots don't store audio output settings

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#1149] opened 2024-08-19 18:05 UTC
**Describe the bug**
A snapshot or zs3 stored without an output selected. (Useful for zs3 to select one of several chains selected by zs3 settings) is restored with the output set to main mix bus.

**To Reproduce**
1. Mak 2 chains 
2. One one chain turn off the Mixbus output to mute the channel
3. Restore snapshot
4. Audio out reset to mixbus

zyncoder: oram (62626a8)
zynthian-ui: oram (8844634)
zynthian-sys: oram (5affa51)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (0327ac4)

**Comment by jofemodo** [comment] 2024-09-13 11:32
It seems solved, or at less i can't reproduce. Please, could you confirm if it's already fixed in latest Oram?

**Closed as completed by jofemodo** 2024-09-13 11:32 UTC
Labels: Can't reproduce
